### ISSUE TITLE
Reddit API returns 401 when running from kubernetes

### ISSUE THREAD

**Issue by timberhill** [flam-flam/dispatcher-service#23]
The API works as expected when running from docker using the [docker compose file](https://github.com/flam-flam/dev-stack/blob/main/compose/docker-compose.yaml) in [dev-stack](https://github.com/flam-flam/dev-stack) repo (`make docker-up`). However, when installing the helm chart (in the [helm-charts](https://github.com/flam-flam/helm-charts) repo, `charts/dispatcher-service`) the API returns a 401 response when trying to fetch the subreddit object.

## Steps to reproduce

- Go to the dispatcher helm chart folder: `cd helm-charts/charts/dispatcher-service`
- Deploy the dispatcher helm chart: `helm upgrade --install dispatcher .`
- List pods: `kubectl get pods`
- Watch the logs: `kubectl logs <PODNAME> --follow`

Example of logs:
```json
{"event": "Setting up reddit instance", "level": "info", "timestamp": "2023-06-02T14:13:47.145796Z"}
{"event": "Setting up the dispatcher", "level": "info", "timestamp": "2023-06-02T14:13:47.426561Z"}
{"event": "Started reddit dispatcher", "level": "info", "timestamp": "2023-06-02T14:13:47.426874Z"}
{"event": "Getting the subreddit object: all", "level": "info", "timestamp": "2023-06-02T14:13:47.427367Z"}
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<RedditDispatcher._stream_comments() done, defined at /src/app/dispatcher.py:60> exception=ResponseException('received 401 HTTP response')>
..... <--- Long traceback here
```

## Sanity check

I have tried to run the code manually in the containers inside docker and kubernetes and got the same results. Below are the steps to reproduce. Assumes the containers are running already.

This uses `praw` package instead of `asyncpraw` because it's much more straightforward to use in a python console. It has equivalent functionality and reproduces the bug.
 
### Docker

<details>
  <summary>Show the output</summary>

`docker exec -it <CONTAINER_ID> sh`

```bash
❯ docker exec -it 67 sh

/src $ python -m pip install praw
Defaulting to user installation because normal site-packages is not writeable
Collecting praw
  Downloading praw-7.7.0-py3-none-any.whl (189 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.4/189.4 kB 3.2 MB/s eta 0:00:00
Collecting prawcore<3,>=2.1
  Downloading prawcore-2.3.0-py3-none-any.whl (16 kB)
Requirement already satisfied: update-checker>=0.18 in /home/appuser/.local/lib/python3.11/site-packages (from praw) (0.18.0)
Collecting websocket-client>=0.54.0
  Downloading websocket_client-1.5.2-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 8.7 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0,>=2.6.0 in /home/appuser/.local/lib/python3.11/site-packages (from prawcore<3,>=2.1->praw) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2023.5.7)
Installing collected packages: websocket-client, prawcore, praw
  WARNING: The script wsdump is installed in '/home/appuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed praw-7.7.0 prawcore-2.3.0 websocket-client-1.5.2
[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

/src $ python
Python 3.11.3 (main, May 11 2023, 23:30:05) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, praw
>>> reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ.get('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher
  File "<stdin>", line 1
    reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ.get('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher
                                                                                                                                        ^
SyntaxError: unterminated string literal (detected at line 1)
>>> -service (by /u/timberhilly)")
KeyboardInterrupt
>>> reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ.get('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher-service (by /u/timberhilly)")
>>> reddit.subreddit('redditdev').random()
Submission(id='11xu7hm')
```

^ Correct response from the API

</details>

### Kuberentes

<details>
  <summary>Show the output</summary>

`kubectl exec --stdin --tty <PODNAME> -- /bin/sh`

```bash
<<K9s-Shell>> Pod: default/dispatcher-dispatcher-service-757ddc7467-tslr4 | Container: dispatcher-service 
/src $ python -m pip install praw
Defaulting to user installation because normal site-packages is not writeable
Collecting praw
  Downloading praw-7.7.0-py3-none-any.whl (189 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.4/189.4 kB 1.3 MB/s eta 0:00:00
Collecting prawcore<3,>=2.1
  Downloading prawcore-2.3.0-py3-none-any.whl (16 kB)
Requirement already satisfied: update-checker>=0.18 in /home/appuser/.local/lib/python3.11/site-packages (from praw) (0.18.0)
Collecting websocket-client>=0.54.0
  Downloading websocket_client-1.5.2-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0,>=2.6.0 in /home/appuser/.local/lib/python3.11/site-packages (from prawcore<3,>=2.1->praw) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/appuser/.local/lib/python3.11/site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2023.5.7)
Installing collected packages: websocket-client, prawcore, praw
  WARNING: The script wsdump is installed in '/home/appuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed praw-7.7.0 prawcore-2.3.0 websocket-client-1.5.2
[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

/src $ python
Python 3.11.3 (main, May 11 2023, 23:50:32) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, praw
>>> reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher-service (by /u/timberhilly)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '_Environ' object is not callable
>>> reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ.get('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher
-service (by /u/timberhilly)")
>>> reddit.subreddit('redditdev').random()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/models/reddit/subreddit.py", line 1038, in random
    self._reddit.get(url, params={"unique": self._reddit._next_unique})
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
                                ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/auth.py", line 373, in refresh
    self._request_token(
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/prawcore/auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
```

</details>

**Comment by timberhill** [comment]
Would be nice to catch the actual request that is sent here, haven't figured out how to to that yet though.

**Comment by timberhill** [comment]
Did some more debugging by running the python in debug mode. 


<details>
  <summary>Test script with debug on</summary>

```python
import logging
from http.client import HTTPConnection

def debug_requests_on():
    '''Switches on logging of the requests module.'''
    HTTPConnection.debuglevel = 1

    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)
    requests_log = logging.getLogger("requests.packages.urllib3")
    requests_log.setLevel(logging.DEBUG)
    requests_log.propagate = True


debug_requests_on()

import os, praw
reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'), client_secret=os.environ.get('REDDIT_CLIENT_SECRET'), user_agent="python:flam-flam-dispatcher-service (by /u/timberhilly)")
print(reddit.subreddit('redditdev').random())
```

</details>

Authorization header differs:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): www.reddit.com:443
send: b'POST /api/v1/access_token HTTP/1.1\r\nHost: www.reddit.com\r\nUser-Agent: python:flam-flam-dispatcher-service (by /u/timberhilly) PRAW/7.7.0 prawcore/2.3.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: close\r\nContent-Length: 29\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: Basic <REDACTED_BASE64>\r\n\r\n'
send: b'grant_type=client_credentials'
reply: 'HTTP/1.1 200 OK\r\n'
```

### The decoded values look like:

#### Docker:

```
<CLIENT_ID>:<CLIENT_SECRET>
```

#### k8s:

```
<CLIENT_ID>
:<CLIENT_SECRET>
```

That newline is the only difference I can see in the request headers - no clue where it's coming from yet. Might need to look into PRAW source.

**Comment by timberhill** [comment]
`echo -n "<token>"  |  base64` FFS
